export const EU_REALMS = [
  "Aegwynn","Aerie Peak","Aggra","Aggramar","Alexstrasza","Alleria","Alonsus",
  "Aman'thul","Ambossar","Anachronos","Anetheron","Antonidas","Anub'arak",
  "Area 52","Argent Dawn","Arthas","Arygos","Ashenvale","Aszune","Auchindoun",
  "Azjol-Nerub","Azshara","Azuregos","Azuremyst","Baelgun","Balnazzar",
  "Blackhand","Blackmoore","Blackrock","Blackscar","Blackwater Raiders",
  "Blackwing Lair","Blade's Edge","Bladefist","Bloodfeather","Bloodhoof",
  "Bloodscalp","Borean Tundra","Boulderfist","Bronze Dragonflight","Bronzebeard",
  "Burning Blade","Burning Legion","Burning Steppes","Chamber of Aspects",
  "Chromaggus","Colinas Pardas","Confrérie du Thorium","Conseil des Ombres",
  "Crushridge","Culte de la Rive noire","Daggerspine","Darkmoon Faire",
  "Darksorrow","Darkspear","Das Konsortium","Das Syndikat","Deathguard",
  "Deathwing","Defias Brotherhood","Dentarg","Der abyssische Rat","Destromath",
  "Dethecus","Die Aldor","Die Arguswacht","Die ewige Wacht","Die Nachtwache",
  "Die Silberne Hand","Die Todeskrallen","Die Unbestechlichen","Doomhammer",
  "Draenor","Dragonblight","Dragonmaw","Drak'thul","Dun Modr","Dun Morogh",
  "Dunemaul","Durotan","Earthen Ring","Emerald Dream","Emeriss","Eonar",
  "Eredar","Eversong","Executus","Exodar","Festung der Stürme","Fordragon",
  "Frostmane","Frostmourne","Frostwhisper","Frostwolf","Genjuros","Ghostlands",
  "Gilneas","Gorgonnash","Grim Batol","Gul'dan","Hakkar","Hellfire","Hellscream",
  "Hyjal","Illidan","Jaedenar","Kael'thas","Karazhan","Kargath","Kiljaeden",
  "Kilrogg","Kirin Tor","Kor'gall","Krag'jin","Krasus","Kul Tiras","Kult der Verdammten",
  "La Croisade écarlate","Laughing Skull","Les Clairvoyants","Les Sentinelles",
  "Lightbringer","Lightning's Blade","Lordaeron","Los Errantes","Lothar",
  "Madmortem","Magtheridon","Mal'Ganis","Malfurion","Malorne","Malygos",
  "Mannoroth","Marécage de Zangar","Mazrigos","Medivh","Minahonda",
  "Moonglade","Mug'thol","Nathrezim","Naxxramas","Nazjatar","Nefarian",
  "Nemesis","Neptulon","Ner'zhul","Nera'thor","Nethersturm","Nordrassil",
  "Norgannon","Nozdormu","Onyxia","Outland","Perenolde","Pozzo dell'Eternità",
  "Proudmoore","Quel'Thalas","Ragnaros","Ravencrest","Ravenholdt","Rexxar",
  "Runetotem","Sanguino","Santovar","Scarshield Legion","Sen'jin","Shadowsong",
  "Shattered Halls","Shattered Hand","Silvermoon","Sinstralis",
  "Skullcrusher","Soulflayer","Spinebreaker","Sporeggar","Steamwheedle Cartel",
  "Stormrage","Stormreaver","Stormscale","Sunstrider","Sylvanas","Taerar",
  "Talnivarr","Tarren Mill","Teldrassil","Temple noir","Terenas","Terokkar",
  "Terrordar","The Maelstrom","The Sha'tar","The Venture Co","Theradras",
  "Thermaplugg","Thrall","Throk'Feroth","Thunderhorn","Tichondrius","Tirion",
  "Todeswache","Trollbane","Turalyon","Twilight's Hammer","Twisting Nether",
  "Tyrande","Uldaman","Ulduar","Uldum","Un'Goro","Ungerer","Ursin","Vashj",
  "Vek'lor","Vek'nilash","Vol'jin","Wildhammer","Wrathbringer","Xavius",
  "Ysera","Ysondre","Zenedar","Zirkel des Cenarius","Zul'jin","Zuluhed"
];